---
include:
- "app/**/*.rb"
exclude:
- test/**/*
- vendor/**/*
- ".bundle/**/*"
- sorbet/**/*.rb
require:
  - actioncable
  - actionmailer
  - actionpack
  - actionview
  - activejob
  - activemodel
  - activerecord
  - activestorage
  - activesupport
reporters:
- rubocop
